course_index_to_name = {
    '0':  'Castle Grounds',
    '6':  'Castle Inside',
    '26': 'Castle Courtyard',
    '9':  'Bob-omb Battlefield',
    '24': "Whomp's Fortress",
    '12': 'Jolly Roger Bay',
    '5':  'Cool, Cool Mountain',
    '4':  "Big Boo's Haunt",
    '7':  'Hazy Maze Cave',
    '8':  'Shifting Sand Land',
    '22': 'Lethal Lava Land',
    '23': 'Dire, Dire Docks',
    '10': "Snowman's Land",
    '11': 'Wet-Dry World',
    '36': "Tall, Tall Mountain",
    '13': 'Tiny-Huge Island',
    '14': 'Tick Tock Clock',
    '15': 'Rainbow Ride',
    '20': 'Secret Aquarium',
    '27': "Princess' Secret Slide",
    '28': 'Cavern of the Metal Cap',
    '29': 'Tower of the Wing Cap',
    '18': 'Vanish Cap under the Moat',
    '31': 'Wing Mario over the Rainbow',
    '17': 'Bowser in the Dark World',
    '30': 'Bowser in the Dark World Fight',
    '19': 'Bowser in the Fire Sea',
    '33': 'Bowser in the Fire Sea Fight',
    '21': 'Bowser in the Sky',
    '34': 'Bowser in the Sky Fight'
}

course_initials_to_index = {
    'grounds': '0',
    'inside':  '6',
    'court':   '26',
    'bob':     '9',
    "wf":      '24',
    'jrb':     '12',
    'ccm':     '5',
    "bbh":     '4',
    'hmc':     '7',
    'ssl':     '8',
    'lll':     '22',
    'ddd':     '23',
    "sl":      '10',
    'wdw':     '11',
    "ttm":     '36',
    'thi':     '13',
    'ttc':     '14',
    'rr':      '15',
    'sa':      '20',
    "pss":     '27',
    'cotmc':   '28',
    'totwc':   '29',
    'vcutm':   '18',
    'wmotr':   '31',
    'bitdw':   '17',
    'bitdwf':  '30',
    'bitfs':   '19',
    'bitfsf':  '33',
    'bits':    '21',
    'bitsf':   '34'
}