strats_list = ['blj', 'c_up_slide', 'use_warp', 'use_shell', 'use_cannon', 'leave_course', 'goto_pu', 'downwarp',
    'uninitialized',
    'standing',
    'start sleeping',
    'sleeping',
    'waking up',
    'panting',
    'standing against wall',
    'coughing',
    'shivering',
    'first person view',
    'stop skidding',
    'walking/running',
    'turning around (1/2)',
    'turning around (2/2)',
    'skidding',
    'decelerating',
    'crawling',
    'start crawling',
    'stop crawling',
    'punch / breakdance',
    'moving punch / breakdance',
    'single jump',
    'single jump landing (1/2)',
    'single jump landing (2/2)',
    'double jump',
    'double jump landing (1/2)',
    'double jump landing (2/2)',
    'triple jump',
    'triple jump landing (1/2)',
    'triple jump landing (2/2)',
    'backflip',
    'steep jump',
    'backflip landing (1/2)',
    'backflip landing (2/2)',
    'pole jump / wall kick',
    'sideflip',
    'sideflip landing (1/2)',
    'sideflip landing (2/2)',
    'long jump',
    'long jump landing (1/2)',
    'long jump landing (2/2)',
    'water jump',
    'freefall',
    'freefall landing (1/2)',
    'freefall landing (2/2)',
    'twirling',
    'twirl landing',
    'ground pound',
    'ground pound landing',
    'air hitting wall',
    'air kick',
    'special triple jump',
    'lava boost landing',
    'quicksand jump landing',
    'riding owl',
    'start sliding',
    'air sitting',
    'ground sitting',
    'stop sitting',
    'air dive',
    'sliding',
    'ground dive',
    'stop sliding/diving',
    'crouching',
    'start crouching',
    'stop crouching',
    'crouch sliding',
    'forward rollout',
    'backward rollout',
    'slide kick',
    'slide kick sliding',
    'stop slide kicking',
    'ledge grab',
    'slow ledge get up (1/2)',
    'slow ledge get up (2/2)',
    'climb down onto ledge',
    'quick ledge get up',
    'holding pole',
    'short pole grab',
    'long pole grab',
    'climbing pole',
    'handstand transition',
    'handstand',
    'handstand jump',
    'start hanging',
    'hanging',
    'swinging',
    'shell riding on ground',
    'shell riding jump',
    'shell riding freefall',
    'in cannon',
    'cannon shot',
    'start teleporting',
    'stop teleporting',
    'flying triple jump',
    'flying',
    'vertical wind',
    'in quicksand',
    'mystery action',
    'shockwave bouncing',
    'shocked',
    'squished',
    'head stuck in ground',
    'butt stuck in ground',
    'feet stuck in ground',
    'grabbed / heaved start',
    'twirling in tornado',
    'burning on ground',
    'hard backward knockback',
    'hard forward knockback',
    'medium backward knockback',
    'medium forward knockback',
    'soft backward knockback',
    'soft forward knockback',
    'ground bonk',
    'death exit landing',
    'backward air knockback',
    'forward air knockback',
    'forward death air',
    'backward death air',
    'fire bounce',
    'fire freefall',
    'soft bonk / let go',
    'lava boost',
    'blown away',
    'thrown',
    'heaved',
    'standing death',
    'quicksand death',
    'electrocution',
    'suffocation',
    'death on stomach',
    'death on back',
    'eaten by bubba',
    'sucked into whirlpool',
    'in water',
    'water action end',
    'drowning',
    'water backward knockback',
    'water forward knockback',
    'water death',
    'water shocked',
    'swim (1/2)',
    'swim (2/2)',
    'flutterkick',
    'water grab',
    'water plunge',
    'metal water standing',
    'metal water walking',
    'metal water falling',
    'metal water fall landing',
    'metal water jump',
    'metal water jump landing',
    'start sliding with an object',
    'panting with an object',
    'standing with an object',
    'standing with a heavy object',
    'picking up an object',
    'stop sliding with an object',
    'placing down an object',
    'picking up Bowser',
    'holding Bowser',
    'releasing Bowser',
    'walking with an object',
    'decelerating with an object',
    'jump with an object',
    'jump landing with an object (1/2)',
    'jump landing with an object (2/2)',
    'freefall with an object',
    'freefall landing with an object (1/2)',
    'freefall landing with an object (2/2)',
    'air sitting with an object',
    'ground sitting with an object',
    'stop sitting with an object',
    'sliding with an object',
    'ground throw',
    'air throw',
    'air throw landing',
    'quicksand jump landing with an object',
    'walking with a heavy object',
    'throwing a heavy object',
    'crazy box hopping',
    'water shell swimming',
    'water throw',
    'in water with an object',
    'water action end with an object',
    'swim with an object (1/2)',
    'swim with an object (2/2)',
    'flutterkick with an object',
    'water jump with an object',
    'metal water standing with an object',
    'metal water walking with an object',
    'metal water falling with an object',
    'metal water fall landing with an object',
    'metal water jump with an object',
    'metal water jump landing with an object',
    'uninitialized',
    'disappeared',
    'intro cutscene',
    'star dance ground (exits)',
    "star dance ground (doesn't exit)",
    'star dance water',
    'falling with star',
    'unlocking door text',
    'text / cutscene',
    'reading text (sign)',
    'waiting for text',
    'free movement',
    'credits',
    'waving',
    'pulling door',
    'pushing door',
    'appearing from door',
    'spinning enter landing',
    'star exit landing',
    'unlocking key door',
    'unlocking door',
    'entering star door',
    'neutral enter landing',
    'putting on hat',
    'grand star cutscene',
    'Peach cutscene',
    'exit warp pipe',
    'spinning enter',
    'star exit sideways',
    'death exit sideways',
    'death exit freefall',
    'death exit downwards',
    'star exit upwards',
    'death exit upwards',
    'star exit downwards',
    'neutral enter',
    'BBH enter jump',
    'BBH enter spinning'
]